apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: training1
  labels:
    name: testing
spec:
  containers:
  - name: testing
    image: bitbull/webserver
    ports:
    - containerPort: 80
